### PR TITLE
Upversion and style cleanup

### LINKED ISSUE #687: Validate Blender 5.0 and 5.1 Support
Hopefully this should have been taken care of with #669 (looking at the list of [5.0 Python changes](https://developer.blender.org/docs/release_notes/5.0/python_api/), there's not much I'm concerned about, except maybe the EEVEE Next internal name change), but given that 5.0 has now entered beta, this is a good time to test against it and see if there's any other bugs we need to take care of. While we're at it, we should also test against the latest Blender 5.1 alpha and see if there's anything we need to take care of. We could also use this opportunity to implement some actions against daily builds [like Brady Johnston did in his BCON talk this year](https://www.youtube.com/watch?v=BM1iSM-G-F0)

Edit by TheDuckCow:

- [x] Fixing seus pbr importing (resolved in https://github.com/Moo-Ack-Productions/MCprep/pull/689)
- [x] Fixing the meshswap QA tests by updating the meshswap file's pig texture (now renamed to temperate pig) (updated locally)
- [x] Fixing the spawner asset, which has a solid core appearing for the spawner, and a bad pig head layout
- [x] Updating entity/meshswap/other spawners to ensure sub collections of `Spawner Exclude` are also auto excluded, as right now it looks like doubles are appearing (resolved in https://github.com/Moo-Ack-Productions/MCprep/pull/689)
- [ ] QA the new colorspace configuration, per post directly below

### PR DESCRIPTION
**Pull request by TheDuckCow**
This should be the last PR for v3.6.2, just doing some final QA testing.

Edit: Uncovered lots of other issues with 5.0 and some gaps in the unit test coverage. So, this PR is now addressing all of that.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Test results at the moment: need to check what I broke in older versions real quick

```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(4.5.3)   	all_tests	70	2	0	No errors
(4.3.1)   	all_tests	70	2	0	No errors
(4.2.3)   	all_tests	70	2	0	No errors
(4.0.2)   	all_tests	70	2	0	No errors
(3.6.2)   	all_tests	70	2	0	No errors
(3.5.1)   	all_tests	70	2	0	No errors
(3.1.0)   	all_tests	70	2	1	test_prep_pbr_seus
(3.0.0)   	all_tests	70	2	1	test_prep_pbr_seus
(2.93.0)   	all_tests	69	3	1	test_prep_pbr_seus
(2.80.75)   	all_tests	68	4	1	test_prep_pbr_seus
```


Edit: hm I did change this shader node, odd it would be failing now. Looking into it

```
======================================================================
ERROR: test_prep_pbr_seus (materials_test.MaterialsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/patrickcrawford/Documents/gits/mcprep/test_files/materials_test.py", line 192, in test_prep_pbr_seus
    new_mat = self._prep_material_test_constructor("seus")
  File "/Users/patrickcrawford/Documents/gits/mcprep/test_files/materials_test.py", line 158, in _prep_material_test_constructor
    improveUiSettings=False)
  File "/Applications/blender 2.80/Blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/tracking.py", line 887, in wrapper
    res = function(self, context)
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/materials/prep.py", line 259, in execute
    options=options
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/materials/generate.py", line 367, in matprep_cycles
    res = matgen_cycles_principled(mat, options)
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/materials/generate.py", line 1563, in matgen_cycles_principled
    texgen_seus(mat, options.passes, nodeInputs, options.use_reflections, options.use_emission_nodes)
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/materials/generate.py", line 1128, in texgen_seus
    location=(-280, -280))
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/materials/generate.py", line 829, in create_node
    node = tree_nodes.new(node_type)
RuntimeError: Error: Node type ShaderNodeSeparateColor undefined
```

Edit two, found the change occurred started in Blender 3.3, so doing version checks based off of that. Testing locally again.

**Comment by TheDuckCow** [comment]
Welp. For whatever reason, Blender had changed the color split node to one format for Blender 3.3 up until 5.0, where it changed exactly back. No idea why (and..... how were my tests passing before, is very bizarre to me).

Now just doing functional QA in each area in case anything else pops up

```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(4.5.3)   	all_tests	70	2	0	No errors
(4.3.1)   	all_tests	70	2	0	No errors
(4.2.3)   	all_tests	70	2	0	No errors
(4.0.2)   	all_tests	70	2	0	No errors
(3.6.2)   	all_tests	70	2	0	No errors
(3.5.1)   	all_tests	70	2	0	No errors
(3.1.0)   	all_tests	70	2	0	No errors
(3.0.0)   	all_tests	70	2	0	No errors
(2.93.0)   	all_tests	69	3	0	No errors
(2.80.75)   	all_tests	68	4	0	No errors
```

**Comment by TheDuckCow** [comment]
Ok as should have been obvious from the above results, blender 5.0 wasn't being included. I've included it now, and sadly, tests are consistently crashing in the middle of the QA mob checks. It is, however, quite consistently happening on the wolf rig. I'm goign to attempt to locally remove the custom py code in case that's a source of the issue.

```
-------------------------------------------------------------------------------
Running tests for (5, 0, 0)...
addon_utils.disable: MCprep_addon not enabled
module changed on disk: '/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/__init__.py' reloading...
Failed to register scene update handler
Failed to register scene update handler
Failed to register scene update handler
Checking blend files
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/effects/geonodes/weather_effects_geo_by_the3pooka.blend
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/effects/collection/tnt_explosion.blend
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/effects/collection/tnt_explosion_instant.blend
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/effects/particle/particles_by_theduckcow.blend
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/mcprep_meshSwap.blend
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/ocelot - HissingCreeper.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/snowgolem - Rymdnisse.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/wandering trader - boxscape.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/Simple Villager Th3Pooka 2.8.blend
Warning: Material Villager Quick Switch Skin could not be converted because of non-trivial alpha blending (need manual adjustment)

None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/villager - Boxscape.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/llama - boxscape.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/Iron Golem - Trainguy.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/Strider - Boxscape.blend
None
QC'ing: /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/wolf - Trainguy.blend
00:00.925  anim.driver      | WARNING Invalid driver - key_blocks["Jaw"].value[0]
00:00.927  blend            | Read blend: "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/MCprep_resources/rigs/friendly/horse - TheDuckCow.blend"
00:00.933  blend.doversion  | WARNING Region type 4 missing in space type "Info" (id: 7) - removing region
00:00.933  blend.doversion  | WARNING Region type 9 missing in space type "Userpref" (id: 19) - removing region
00:00.933  blend.doversion  | WARNING Region type 5 missing in space type "Buttons" (id: 4) - removing region
Writing: /var/folders/n1/c3slyy8x14l28nk2s_pc9j3w0000gn/T/wolf - Trainguy.crash.txt

Removing:  /Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/mcprep_addon_tracker.json
Removing:  /Users/patrickcrawford/Documents/gits/mcprep/mcprep_addon_trackerid.json
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
Compiled in 35.3s + tests ran in 1.2s
Total of 36.5s with exit code 1
```

File: MCprep_addon/materials/generate.py [hunk 1]
```diff
@@ -1121,8 +1121,16 @@ def texgen_seus(mat: Material, passes: Dict[str, Image], nodeInputs: List, use_r
 		name="Smooth Inverse",
 		label="Smooth Inverse",
 		location=(-80, -280))
+	sep_node = ""
+	if util.min_bv((5, 0)):
+		sep_node = "ShaderNodeSeparateRGB"
+	elif util.min_bv((3, 3)):
+		sep_node = "ShaderNodeSeparateColor"
+	else:
+		sep_node = "ShaderNodeSeparateRGB"
```
Comment (StandingPadAnimations) [inline MCprep_addon/materials/generate.py:1128]: Slight nitpick: since 3.3-5.0 is the only exception so far, I think it would make sense to simplify this down:


```suggestion
	sep_node = "ShaderNodeSeparateRGB"
	if util.min_bv((3, 3)) and not util.min_bv((5, 0)):
		sep_node = "ShaderNodeSeparateColor"
```

File: MCprep_addon/materials/generate.py [hunk 2]
```diff
@@ -1145,9 +1153,9 @@ def texgen_seus(mat: Material, passes: Dict[str, Image], nodeInputs: List, use_r
 	saturateMixOut = get_node_socket(nodeSaturateMix, is_input=False)
 
 	# Links the nodes to the reroute nodes.
-	RED = "R" if util.min_bv((5, 0)) else "Red"
-	BLUE = "B" if util.min_bv((5, 0)) else "Blue"
-	GREEN = "G" if util.min_bv((5, 0)) else "Green"
+	RED = "Red" if (3, 3) < bpy.app.version < (5, 0) else "R"
+	BLUE = "Blue" if (3, 3) < bpy.app.version < (5, 0) else "B"
+	GREEN = "Green" if (3, 3) < bpy.app.version < (5, 0) else "G"
```
Comment (StandingPadAnimations) [inline MCprep_addon/materials/generate.py]: Might be a good time to create some sort of `in_bv_range` function in `util.py`, given both the above conditional and this section. Something like this:

```py
def in_bv_range(lower_bound: Tuple, upper_bound: Tuple, inclusive: bool = True) -> bool:
    return min_bv(lower_bound, inclusive) and not min_bv(upper_bound, inclusive)
```

File: MCprep_addon/__init__.py [hunk 3]
```diff
@@ -41,7 +41,7 @@
 bl_info = {
 	"name": "MCprep",
 	"category": "Object",
-	"version": (3, 6, 1, 3),
+	"version": (3, 6, 2),
 	"blender": (2, 80, 0),
```
Comment (StandingPadAnimations) [inline MCprep_addon/__init__.py]: Should probably update this to 2.83, since we no longer include 2.8-2.82 in the test suite or the BpyBuild config

Comment (StandingPadAnimations) [reply MCprep_addon/__init__.py]: Speaking of this, we should also update the `_blender_manifest.toml` file. While we don't provide extension builds currently, we do have the configuration (minus `build_extension` being set to `false`) and actions needed to build an extension build, so we also need to update the `version` property in the manifest

https://github.com/Moo-Ack-Productions/MCprep/blob/7fdcf6f59c5129e7bda45d9cdbce78a4312a2b44/MCprep_addon/_blender_manifest.toml#L4

File: MCprep_addon/materials/generate.py (hunk 2 above)
Comment (TheDuckCow) [reply MCprep_addon/materials/generate.py]: Per above, only one conditional now thankfully. Longer term, I'm seeing less of a need for this these bv utils as we no longer support any Blender version that doesn't yet have the bpy.app.version field (which is why the abstraction function was added anyhow). They don't save that much space and are awkward to place a tuple in (double nesting). The bv4 and bv5 ones I can see an argument for though since they are shorter.

File: MCprep_addon/materials/generate.py (hunk 1 above)
Comment (TheDuckCow) [reply MCprep_addon/materials/generate.py:1128]: Sure, I also realize that I got it mixed up partially since by tests weren't covering 5.0 like I thought, there's only one conditional now actually, not as crazy as I thought it was initially.

**Comment by TheDuckCow** [comment]
Alright, that solves one of the unit tests...

Others remaining:

## test_qa_rigs

Manually disabling for now, simply removing the wolf rig wasn't enough to get it working again (though using the wolf rig as a user seems to function fine). It's hard crashing Blender so makes it challenging to debug, could even mean it's some prior tested rig that is actually causing the issue. Certainly are a number of driver warnings.


## test_collection_effect_spawner

```
# Finally, perform the main operation of shifting keyframes.
	for action in actions:
		for fcurve in action.fcurves:
```

Results in:

```
Traceback (most recent call last):
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/tracking.py", ... truncatedError: Python: Traceback (most recent call last):
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/tracking.py", line 887, in wrapper
    res = function(self, context)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/spawner/effects.py", line 1141, in execute
    add_collection_effect(context, effect, self.location, self.frame)
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/spawner/effects.py", line 208, in add_collection_effect
    offset_animation_to_frame(coll, frame)
  File "/Users/patrickcrawford/Documents/gits/mcprep/MCprep_addon/spawner/effects.py", line 733, in offset_animation_to_frame
    for fcurve in action.fcurves:
                  ^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute 'fcurves'
```

Makes sense given the partial updates towards the slotted action system, need to investigate what further to change. ([ref](https://developer.blender.org/docs/release_notes/5.0/python_api/#animation-rigging))

**Comment by TheDuckCow** [comment]
Fcurves issue resolved, and another issue found, while trying to use the item spawner in 5.0 (really, this is just an issue of hte UV tools). Also affects the particle sequence spawner.

```
Error found at source/blender/draw/intern/draw_handle.hh:312 in particles_matrix.
Traceback (most recent call last):
  File "/Users/patrickcrawford/Library/Application Support/Blender/5.0/scripts/addons/MCprep_addon/tracking.py", line 887, in wrapper
    res = function(self, context)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickcrawford/Library/Application Support/Blender/5.0/scripts/addons/MCprep_addon/materials/uv_tools.py", line 186, in execute
    ret = self.scale_uv_faces(context.object, self.scale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickcrawford/Library/Application Support/Blender/5.0/scripts/addons/MCprep_addon/materials/uv_tools.py", line 219, in scale_uv_faces
    if not uv.data[loop_ind].select and self.selected_only is True:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MeshUVLoop' object has no attribute 'select'

```

Updated summary, things todo:
- [x] QA rigs still an open thing to look into
- [x] Missing unit tests for the UV alpha select/scale, and for combine images/materials
- [x] Actually fix uv scale not working in Blender 5.0
- [x] Combine Materials and Combine Images is also broken -> Edit: now it seems to be working fine for both? Not sure what happened the first time I tested it
- [x] Meshswap works, but doesn't seem to be meshswapping tall grass (gah, the number of renamings that has gone through, makes this mapping so difficult)
    - Need to check again with a later minecraft export, this was on an old map it failed to meshswap tall grass (1block height)
- [x] Also seeing meshswap not working well for crafting tables anymore, not cleaning up the side faces.
- [ ] Animate textures: inside MCprep texturepack (other two modes work fine)

**Comment by TheDuckCow** [comment]
Once again mostly narrowed in on what I need to change, just need to find the way to replace the select operator, per API [doc changes here](https://developer.blender.org/docs/release_notes/5.0/python_api/#mesh) (removal of `bmesh.types.BMLoopUV.select` and introduction of `. uv_select_face`... wish they gave the class name this operator was added to).

Stepping out for a bit. Really hoping to wrap up and push out at least an initial release, otherwise we'll get a wave of issues when Blender 5.0 launches tomorrow.

**Comment by TheDuckCow** [comment]
I uncovered there was actually only one problematic rig for the tests - the horse blend file (by yours truly). Removing this rig from the build, all tests pass. Crashes otherwise. The fact that I saw the wolf rig as the last one was a red herring apparently, as there's nothing wrong with it.

Oddly, spawning the horse in the UI itself worked perfectly fine though. But anyhow, I was able to fix the test runner by saving the file in 2.83 (upgrading it to the last version it was saved in, 2.79). Looking green now:

```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(5.0.0)   	all_tests	74	2	0	No errors
(4.5.3)   	all_tests	74	2	0	No errors
(4.3.1)   	all_tests	74	2	0	No errors
(4.2.3)   	all_tests	74	2	0	No errors
(4.0.2)   	all_tests	74	2	0	No errors
(3.6.2)   	all_tests	74	2	0	No errors
(3.5.1)   	all_tests	74	2	0	No errors
(3.1.0)   	all_tests	74	2	0	No errors
(3.0.0)   	all_tests	74	2	0	No errors
(2.93.0)   	all_tests	73	3	0	No errors
(2.80.75)   	all_tests	72	4	0	No errors
Compiled in 40.4s + tests ran in 243.8s
```

Though I've made minor other changes, I've applied the feedback from @StandingPadAnimations so I'm going to proceed to creating the release candidate shortly.
